[package]
name = "keos-project3"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "1.2.1"

keos = { path ="../../keos" }
keos-project1 = { path ="../keos-project1" }
keos-project2 = { path ="../keos-project2" }