[package]
name = "abyss"
version = "0.1.0"
edition = "2024"

[lib]
test = false

[dependencies]
bitflags = "1.3.2"
num_enum = { version = "0.5", default-features=false }
arrayvec = { version = "0.7.6", default-features=false }

[features]
default = []