[package]
name = "grading_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0.34", features = ["full", "fold"] }

[build-dependencies]
proc-macro2 = "1.0"